
services:
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_ADMIN_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_ADMIN_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongodb:27017/"
      ME_CONFIG_SITE_BASEURL: /admindb/
    depends_on:
      - mongodb

  nestjs:
    build:
      context: ./user-service
    environment:
      PORT: 3001
      MONGO_URI: "mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongodb:27017/"
      JWT_SECRET: "${JWT_SECRET}"
    volumes:
      - ./user-service:/app

  colorizer:
    build:
      context: ./colorization-service
    tty: true
    volumes:
      - ./colorization-service:/app

  nextjs:
    build:
      context: ./site
    volumes:
      - ./site:/app

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nestjs
      - nextjs
      - mongo-express
      - colorizer

volumes:
  mongodb_data: